import { SITE } from '@/config/site'
import { absoluteUrl } from './utils'

export const orgSchema = {
  '@context': 'https://schema.org',
  '@type': ['Store', 'Organization', 'LocalBusiness'],
  name: SITE.name,
  description: SITE.brandStatement,
  url: absoluteUrl('/'),
  legalName: SITE.legalName,
  foundingDate: String(SITE.foundingYear),
  foundingLocation: {
    '@type': 'Place',
    address: {
      '@type': 'PostalAddress',
      addressLocality: SITE.address.locality,
      addressRegion: SITE.address.region,
      postalCode: SITE.address.postcode,
      addressCountry: SITE.address.country,
    },
  },
  address: {
    '@type': 'PostalAddress',
    addressLocality: SITE.address.locality,
    addressRegion: SITE.address.region,
    postalCode: SITE.address.postcode,
    addressCountry: SITE.address.country,
  },
  email: SITE.email.replace('@', '&#64;'),
  telephone: SITE.phone,
  taxID: `ABN ${SITE.abn}`,
  areaServed: 'AU',
  priceRange: '$$',
  sameAs: SITE.sameAs,
  knowsAbout: [
    'Australian prop money',
    'Prop money Australia',
    'Prop Australian money',
    'Fake Australian money prop',
    'Realistic fake money Australia',
    'AU prop money',
    'Prop Australian currency',
    'Prop money detector Australia',
    'Prop money in Australia',
    'Fake note Australia',
    'Fake coins',
    'Fake money detector',
    'Fake print money',
    'AUS prop money',
    'Proping of money',
    'Fake note',
    'Prop money AU',
    'Australian fake money',
    'Prop cash',
    'Fake $100 Australia',
    'Pokies fake money',
    'Props money',
    'Australian prop money detector',
    'Fake Australian dollar',
    'Fake prop Australian money',
    'Fake money print',
    'Fake money printable',
    'Fake money tester pen',
    'How to tell prop money Australia',
    'Prop money AUD',
    'Australia prop money',
    'Australian prop money',
    'Prop money Australia penalty',
    'Prop money tester',
    'Fake cash detector',
    'Fake money big W',
    'Fake money flex',
    'Fake notes Australia',
    'How to tell if money is fake Australia',
    'Make fake money',
    'Prop AUS money',
    'Ready prop money',
    'Realistic fake money Australia online',
    'What is prop money',
    'Best prop money',
    'Best fake money',
  ],
}

export const websiteSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: SITE.name,
  url: absoluteUrl('/'),
  potentialAction: {
    '@type': 'SearchAction',
    target: `${absoluteUrl('/search/')}?q={search_term_string}`,
    'query-input': 'required name=search_term_string',
  },
}
